# Generated by Django 4.1.7 on 2023-04-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
